version: 0.0
Resources:
    - TargetService:
        Type: AWS::ECS::Service
        Properties:
            TaskDefinition: AlbumTaskDefinition
            LoadBalancerInfo:
                ContainerName: "AlbumContainer"
                ContainerPort: 80

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: AlbumContainer
        image: 078445965761.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:${{github.run_number}}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: AlbumServiceBlueGreen
        cluster: AlbumCluster
        wait-for-service-stability: true